#SPDX-License-Identifier: MIT-0
---
# tasks file for test_roles
- name: Update and upgrade apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes

- name: Install Docker
  ansible.builtin.apt:
    name: "docker.io"
    state: present
  
- name: Install Docker CLI
  ansible.builtin.apt:
    name: docker-compose
    state: present

- name: Start Docker services
  service:
    name: docker
    state: started
    enabled: true
